# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-20 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('credit', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.DecimalField(decimal_places=1, max_digits=4)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Professionalclass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('faculty', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_number', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('sex', models.CharField(max_length=32)),
                ('nation', models.CharField(max_length=32)),
                ('birthday', models.DateField()),
                ('birthplace', models.CharField(max_length=32)),
                ('pclass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.Professionalclass')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('major', models.CharField(max_length=32)),
                ('en_time', models.DateField()),
                ('political', models.CharField(max_length=32)),
                ('edu_ba', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('sex', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='student_detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.StudentDetail'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(through='app01.Grade', to='app01.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Teacher'),
        ),
    ]
