# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-14 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='123', max_length=32),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='123', max_length=32),
        ),
    ]
