# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-14 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20181214_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_number',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
