# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-01 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_commit'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='ability',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='experience',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='hobby',
            field=models.TextField(null=True),
        ),
    ]
