# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-01 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20190101_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='ability',
            field=models.TextField(default='...', null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='address',
            field=models.CharField(default='...', max_length=64),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='edu_ba',
            field=models.CharField(default='...', max_length=32),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='email',
            field=models.EmailField(default='...@...', max_length=254),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='experience',
            field=models.TextField(default='...', null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='hobby',
            field=models.TextField(default='...', null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='major',
            field=models.CharField(default='...', max_length=32),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='phone',
            field=models.CharField(default='...', max_length=32),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='political',
            field=models.CharField(default='...', max_length=32),
        ),
    ]
