# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-01 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20190101_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='ability',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='address',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='edu_ba',
            field=models.CharField(default='本科', max_length=32),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='experience',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='hobby',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='major',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='phone',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='political',
            field=models.CharField(max_length=32),
        ),
    ]
