# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-01 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_auto_20190101_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='en_time',
            field=models.DateField(null=True),
        ),
    ]
